module.exports = [
  { name: 'Ariyalur', emailLocal: 'ariyalur', pinCode: '621704', code: 'Ari' },
  { name: 'Chennai', emailLocal: 'chennai', pinCode: '600001', code: 'Che' },
  { name: 'Coimbatore', emailLocal: 'coimbatore', pinCode: '641001', code: 'Cbe' },
  { name: 'Cuddalore', emailLocal: 'cuddalore', pinCode: '607001', code: 'Cud' },
  { name: 'Dharmapuri', emailLocal: 'dharmapuri', pinCode: '636701', code: 'Dha' },
  { name: 'Dindigul', emailLocal: 'dindigul', pinCode: '624001', code: 'Din' },
  { name: 'Erode', emailLocal: 'erode', pinCode: '638001', code: 'Ero' },
  { name: 'Kanchipuram', emailLocal: 'kanchipuram', pinCode: '631501', code: 'Kan' },
  { name: 'Kanyakumari', emailLocal: 'kanyakumari', pinCode: '629001', code: 'Kny' },
  { name: 'Karur', emailLocal: 'karur', pinCode: '639001', code: 'Kar' },
  { name: 'Krishnagiri', emailLocal: 'krishnagiri', pinCode: '635001', code: 'Kri' },
  { name: 'Madurai', emailLocal: 'madurai', pinCode: '625001', code: 'Mad' },
  { name: 'Nagapattinam', emailLocal: 'nagapattinam', pinCode: '611001', code: 'Nag' },
  { name: 'Namakkal', emailLocal: 'namakkal', pinCode: '637001', code: 'Nam' },
  { name: 'Nilgiris (Ooty)', emailLocal: 'nilgiris', pinCode: '643001', code: 'Nil' },
  { name: 'Perambalur', emailLocal: 'perambalur', pinCode: '621212', code: 'Per' },
  { name: 'Pudukkottai', emailLocal: 'pudukkottai', pinCode: '622001', code: 'Pud' },
  { name: 'Ramanathapuram', emailLocal: 'ramanathapuram', pinCode: '623501', code: 'Ram' },
  { name: 'Salem', emailLocal: 'salem', pinCode: '636001', code: 'Sal' },
  { name: 'Sivaganga', emailLocal: 'sivaganga', pinCode: '630561', code: 'Siv' },
  { name: 'Thanjavur', emailLocal: 'thanjavur', pinCode: '613001', code: 'Tha' },
  { name: 'Theni', emailLocal: 'theni', pinCode: '625531', code: 'The' },
  { name: 'Thoothukudi', emailLocal: 'thoothukudi', pinCode: '628001', code: 'Tut' },
  { name: 'Tiruchirappalli', emailLocal: 'tiruchirappalli', pinCode: '620001', code: 'Tri' },
  { name: 'Tirunelveli', emailLocal: 'tirunelveli', pinCode: '627001', code: 'Tir' },
  { name: 'Tiruppur', emailLocal: 'tiruppur', pinCode: '641601', code: 'Tup' },
  { name: 'Tiruvallur', emailLocal: 'tiruvallur', pinCode: '602001', code: 'Trv' },
  { name: 'Tiruvannamalai', emailLocal: 'tiruvannamalai', pinCode: '606601', code: 'Tva' },
  { name: 'Tiruvarur', emailLocal: 'tiruvarur', pinCode: '610001', code: 'Tvr' },
  { name: 'Vellore', emailLocal: 'vellore', pinCode: '632001', code: 'Vel' },
  { name: 'Viluppuram', emailLocal: 'viluppuram', pinCode: '605602', code: 'Vil' },
  { name: 'Virudhunagar', emailLocal: 'virudhunagar', pinCode: '626001', code: 'Vir' }
]
