apiVersion: v1
kind: Service
metadata:
  name: nexora-backend
  namespace: nexora

spec:
  type: ClusterIP

  selector:
    app: nexora-backend

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000